<!DOCTYPE html>
<html>
    <head>
        <title>Email regex pattern tester</title>
    </head>
    <body>
        <header>
            <h1>Email regex pattern tester</h1>
            <p>An effort to stop crappy regex patterns from spreading</p>
        </header>
        <main>
            <?php echo $content; ?>
        </main>
        <footer>
            <ul>
                <li>Copyright © <?php echo (new DateTime())->format('Y'); ?> <a href="https://pieterhordijk.com">Pieter Hordijk</a></li>
            </ul>
        </footer>
    </body>
</html>
